### ISSUE TITLE
Piece size not power of two

### ISSUE THREAD

**Issue by Kiwi-Torrent-Research** [rndusr/torf#29]
MetainfoError is raised if piece size is not a power of two.  This behaviour is incorrect.

From https://blog.libtorrent.org/2020/09/bittorrent-v2/
In v1 torrents, the size of a piece is not restricted by the specification. It doesn’t make much sense to have a piece smaller than the block size of 16 kiB, but it’s not disallowed. The vast majority of torrents that are created use a power-of-two piece size, but there are a few outliers that are not, but still divisible by 16 kiB

I propose the is_power_of_2 check be replaced by a is_divisible_by_16_kib check.

**Comment by rndusr** [comment]
> I propose the is_power_of_2 check be replaced by a is_divisible_by_16_kib check.

Sounds reasonable and should be very simple to implement.

> I also get "Invalid metainfo: ['info']['name'] must be str, not bytes" when the name (or a filename) contain a non ascii character.
> I think this is caused by the bdecoder returning bytes if the string contains a non ascii character.

bdecode doesn't have a concept of strings, torf tries to decode bytes with UTF-8
and defaults to bytes if that doesn't work. (See _utils.decode_value())

But torf.Torrent.validate() expects ['info']['name'] to be str. This can also be
fixed easily by passing (str, bytes) instead of (str,) to assert_type().

We could also use chardet https://pypi.org/project/chardet/ but I'm not sure
this is a good idea. It probably works well with proper language, but torrent
names tend to be quite short and they can be ~SOOPER~ [L337] so that probably
won't work well in many cases.
https://chardet.readthedocs.io/en/latest/faq.html#isnt-that-impossible

**Comment by rndusr** [comment]
I don't providing the torrent name as bytes is the way to got. It would break
torf for pretty much all projects that depend on torf. And the exact same issue
would still have to be solved, but many times.

I think decoding with strict='replace' is a good idea. If there is demand for
it, it would be possible to add a "encoding" parameter when reading a torrent
file.

**Comment by rndusr** [comment]
I think I've fixed both issues in 4.2.0.

I hope this works better for you.
