### ISSUE TITLE
Add link to torf-gui in readme

### ISSUE THREAD

**Issue by SavageCore** [rndusr/torf#32]
Hey

I decided to port dottorrent-gui to torf

https://github.com/SavageCore/torf-gui

Do you want to add this to the readme?

**Comment by rndusr** [comment]
Thank you for your effort, but this doesn't seem quite ready yet.

The installation fails: "No such file or directory: 'README.rst'".
You renamed README.rst to README.md, but didn't notify setup.py about it.

https://github.com/SavageCore/torf-gui/blob/main/torfGUI/gui.py#L113
torf doesn't have an `exceptions` module and no `EmptyInputException`.
(I'm surprised this doesn't immediately raise an exception.)

Dependencies are *really* outdated.
Python 3.6 has been EOL (no security patches) since 2022:
https://devguide.python.org/versions/#versions
PyQT5 5.7 is from 2016!

The screenshots look weird. Like some columns of pixels were removed to reduce
their width?

Sorry, but I don't want to endorse this in its current state. It really does
look quick and dirty and not like something I would recommend to anyone.

**Comment by SavageCore** [comment]
Thanks for the feedback, I will get those issues sorted out! 

Did you install it from pip or source?

Yeah, screenshots I will have to try and retake on another device, that's just how it looks on my new [monitor](https://www.rtings.com/monitor/reviews/lg/27gr95qe-b#test_4264).. I'm using MacType to try to better the clarity and some stuff renders like that.

**Comment by rndusr** [comment]
I installed with these commands in the cloned directory:

    python3 -m venv test-venv
    venv-activate test-venv
    pip install --editable '.'

I always do a test install before a new release.

I would also recommend writing some tests with pytest and setting up tox with
pyenv. Then you can just run `tox` and it runs all tests for each supported
python version.

**Comment by rndusr** [comment]
Looking much better now!

I've added the link now.

Another issue: Under "Torrent options", I think you mix up the number of pieces
and piece size in bytes. Try selecting a small-ish file and select 16 MiB and it
says "16777216 pieces @ 1 byte each".
